import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./_providers/Providers";

const futuraExtraBold = localFont({
  src: [
    {
      path: "./_fonts/Futura-Condensed-Extra-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-futura-extra-bold",
});

const HelveticaNow = localFont({
  src: [
    {
      path: "./_fonts/helvetica-now-text-regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./_fonts/helvetica-now-text-medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./_fonts/helvetica-now-text-bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Nike - Shoes E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${futuraExtraBold.variable} antialiased overflow-x-hidden ${HelveticaNow.className}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
